#!/bin/bash

/bin/bash ./chef/run_chef-solo.sh

cd test/
nosetests --cover-erase --with-xunit --xunit-file output/nosetests.xml --with-xcoverage
python-coverage xml -o output/coverage.xml $(find ../src/ -type f -name \*.py | while read P; do readlink -f $P; done | tr "\n" " ")
cd -
